PoemonRepo/Pages/FightingCage/ChatRooms.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PokemonRepo.Domain.DbModels;
using PokemonRepo.DTO.DbModels;

namespace PokemonRepo.UI.Pages.FightingCage
{
    public class ChatRoomsModel : PageModel
    {
        private readonly DbHandler _dbHandler;
        public List<ChatRoom> chatRooms { get; set; }

        public ChatRoomsModel(DbHandler dbHandler)
        {
            _dbHandler = dbHandler;
        }
        public async Task OnGet()
        {
            chatRooms = await _dbHandler.GetAllChatRooms();
        }
    }
}

PoemonRepo/Pages/FightingCage/CreateChatroom.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PokemonRepo.Domain;
using PokemonRepo.Domain.DbModels;
using PokemonRepo.DTO;
using PokemonRepo.DTO.DbModels;

namespace PokemonRepo.UI.Pages.FightingCage
{
    public class CreateChatroomModel : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly DbHandler _dbHandler;
        public ChatRoom Chatroom { get; set; }

        [BindProperty]
        [Required]
        public string ChatRoomName { get; set; }

        [BindProperty]
        [Required]
        public string ChatRoomDescription { get; set; }
        public CreateChatroomModel(UserManager<ApplicationUser> userManager, DbHandler dbHandler )
        {
            _userManager = userManager;
            _dbHandler = dbHandler;
        }
        public void OnGet()
        {
          
        }
        public async Task<IActionResult> OnPost()
        {
            if(ModelState.IsValid)
            {
                var user = await _userManager.GetUserAsync(HttpContext.User);
                var chatroom = new ChatRoom()
                {
                    ChatRoomName = ChatRoomName,
                    Description = ChatRoomDescription,
                    Owner = user,

                };

                var result = await _dbHandler.AddChatRoom(chatroom);
                if (result)
                {
                    return RedirectToPage("/FightingCage/ChatRooms");
                }

            }
            return Page();
        }
    }
}

PoemonRepo/Pages/FightingCage/EditProfile.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Caching.Memory;
using Newtonsoft.Json;
using PokemonRepo.Application;
using PokemonRepo.Data;
using PokemonRepo.Domain;
using PokemonRepo.DTO;

namespace PokemonRepo.UI.Pages.FightingCage
{
    public class EditProfileModel : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly DatabaseContext _dbContext;

        public ApplicationUser ProfileUser { get; set; }
        [BindProperty]
        public string Username { get; set; }
        [BindProperty]
        [Required(ErrorMessage = "Enter old password!")]
        public string Password { get; set; }
        [BindProperty]
        [Required(ErrorMessage = "Enter new or same password!")]
        public string Email { get; set; }
        [BindProperty]
        [Required]
        public string NewPassword { get; set; }
        [BindProperty]
        public IFormFile Photo { get; set; }
        [BindProperty]
        public string AboutMe { get; set; }
        [BindProperty]
        public string FavoritePok { get; set; }
        [BindProperty]
        public List<PokemonModel> Pokemons { get; set; }
        public List<PokemonModel> FavoritePokemons { get; set; }

        public List<string> pokemons { get; set; }



        public EditProfileModel( UserManager<ApplicationUser> userManager, IWebHostEnvironment webHostEnvironment, DatabaseContext dbContext)
        {
            pokemons = new List<string>();
            _userManager = userManager;
            _webHostEnvironment = webHostEnvironment;
            _dbContext = dbContext;
        }
        public async Task OnGet()
        {
            var pokemonNames = Enum.GetValues(typeof(PokemonNames)).Cast<PokemonNames>();
            foreach (var pokemon in pokemonNames)
            {
                pokemons.Add(pokemon.ToString().ToLower());
            }
            ProfileUser = await _userManager.GetUserAsync(User);
        }
        public async Task<IActionResult> OnPost()
        {
            ProfileUser = await _userManager.GetUserAsync(User);
            if (ModelState.IsValid)
            { 
                var result = await _userManager.ChangePasswordAsync(ProfileUser, Password, NewPassword);
                if(result.Succeeded)
                {

                    if (Photo != null)
                    {

                        // Create folder

                        string folder = Path.Combine(_webHostEnvironment.WebRootPath, "images");

                        if (!Directory.Exists(folder))
                        {
                            Directory.CreateDirectory(folder);
                        }

                        // Delete existing photo
                        DeleteExistingPhoto(folder, ProfileUser);

                        // Upload new photo

                        string uniqueFileName = UploadNewPhoto(folder, ProfileUser);
                        ProfileUser.PhotoPath = uniqueFileName;
                    }
                    
                        // Update repo with new photopath
                        ProfileUser.UserName = Username;
                        ProfileUser.NormalizedUserName = Username;
                        ProfileUser.Email = Email;
                        ProfileUser.NormalizedEmail = Email;
                        ProfileUser.AboutMe = AboutMe;
                        ProfileUser.FavoritPokemon = FavoritePok;

                        _dbContext.Users.Update(ProfileUser);
                        await _dbContext.SaveChangesAsync();

                        return RedirectToPage("/FightingCage/MyProfile");
                }
                foreach(var errors in result.Errors)
                {
                    ModelState.AddModelError("", errors.Description);
                }
            }
              
            return Page();
        }

        private string UploadNewPhoto(string folder, ApplicationUser user)
        {
            string uniqueFileName = String.Concat(Guid.NewGuid().ToString(), "-",  user.UserName, ".jpg");

            string newFile = Path.Combine(folder, uniqueFileName);

            using (var fileStream = new FileStream(newFile, FileMode.Create))
            {
                Photo.CopyTo(fileStream);
            }

            return uniqueFileName;
        }

        private void DeleteExistingPhoto(string folder, ApplicationUser user)
        {
            string oldFile = Path.Combine(folder, user.PhotoPath);

            if (System.IO.File.Exists(oldFile))
            {
                System.IO.File.Delete(oldFile);
            }
        }
    }
}

PoemonRepo/Pages/FightingCage/MyProfile.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PokemonRepo.DTO;

namespace PokemonRepo.UI.Pages.FightingCage
{
    public class MyProfile : PageModel
    {

        private readonly SignInManager<ApplicationUser> _signInManager;

        private readonly IWebHostEnvironment _webHostEnvironment;
        public ApplicationUser ProfileUser { get; set; }
        public int counter { get; set; }
        public MyProfile(SignInManager<ApplicationUser> signOutManager, IWebHostEnvironment webHostEnvironment)
        {
            _signInManager = signOutManager;
            _webHostEnvironment = webHostEnvironment;
        }
        public async Task OnGet()
        {
           ProfileUser = await _signInManager.UserManager.GetUserAsync(User);
        }
    }
}

PoemonRepo/Pages/FightingCage/ThisChatroom.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PokemonRepo.Domain;
using PokemonRepo.Domain.DbModels;
using PokemonRepo.DTO;
using PokemonRepo.DTO.DbModels;

namespace PokemonRepo.UI.Pages.FightingCage
{
    public class ThisChatroomModel : PageModel
    {
        private readonly DbHandler _dbhandler;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly DatabaseContext _dbContext;

        public ApplicationUser AppUser { get; set; }

        [BindProperty]
        public ChatRoom ThisChatroom { get; set; }
        [BindProperty]
        public List<ChatMessage> Messages { get; set; }
        [BindProperty]
        public string ThisMessage { get; set; }
        [BindProperty]
        public int ChatRoomid { get; set; }
        [BindProperty]
        public int ChatMessageid { get; set; }

        public bool IsEditMode { get; set; }

        public ThisChatroomModel(DbHandler dbhandler, UserManager<ApplicationUser> userManager, DatabaseContext dbContext)
        {
            _dbhandler = dbhandler;
            _userManager = userManager;
            _dbContext = dbContext;
        }
        public async Task OnGet(int id, bool isEdit = false, int chatMessageId = 0)
        {
            IsEditMode = isEdit;
            ChatMessageid = chatMessageId;
            Messages = await _dbhandler.GetAllChatMessages(id);
            Messages = Messages.OrderByDescending(m => m.Date).ToList();
            ThisChatroom = await _dbhandler.GetChatRoom(id);
            AppUser = await _userManager.GetUserAsync(User);
        }
        public async Task<IActionResult> OnPost()
        {
            var message = new ChatMessage()
            {
                Message = ThisMessage,
                User = await _userManager.GetUserAsync(HttpContext.User),
                ChatRoom = await _dbhandler.GetChatRoom(ChatRoomid),
                Date = DateTime.Now
            };
            
            await _dbhandler.AddMessage(message);

            return RedirectToPage("ThisChatroom", new { id = ChatRoomid });
        }
        public async Task<IActionResult> OnPostDelete()
        {
            await _dbhandler.DelteMessage(ChatMessageid);
            return RedirectToPage("ThisChatRoom", new { id = ChatRoomid });
        }

        public async Task<IActionResult> OnPostEdit()
        {            
            return RedirectToPage("ThisChatRoom", new { id = ChatRoomid, isEdit = true, chatMessageId = ChatMessageid});
        }
        public async Task<IActionResult> OnPostDoneEdit()
        {
            var chatmessage = await _dbContext.ChatMessages.FirstOrDefaultAsync(c => c.ChatMessageId == ChatMessageid);
            if(chatmessage != null && !String.IsNullOrEmpty(ThisMessage))
            {
                chatmessage.Message = ThisMessage;
                _dbContext.ChatMessages.Update(chatmessage);
                await _dbContext.SaveChangesAsync();
    
            }
            else if(String.IsNullOrEmpty(ThisMessage))
            {
               await _dbhandler.DelteMessage(ChatMessageid);
            }
            return RedirectToPage("ThisChatRoom", new { id = ChatRoomid });
        }
    }
}

PoemonRepo/Pages/FightingCage/ChatRooms.cshtml
@page
@model PokemonRepo.UI.Pages.FightingCage.ChatRoomsModel
@{
}
<div class="row">
    <a asp-page="CreateChatroom">Create new room</a>
</div>
<div class="row" style="margin-top: 20px;">
    @for (int i = 0; i < @Model.chatRooms.Count; i++)
    {
            @if(i%2==0)
                    {
                        @:</div><div class="row" style="margin-top: 20px;">
                    }
            <div class="col-6">
                <div class="card" style="border: 5px solid yellow;">
                    <div class="card-header" style="background: rgb(255,255,255); background: linear-gradient(0deg, rgba(255,255,255,1) 0%, rgba(0,0,0,1) 77%);">
                        <div class="row">
                            <div class"col-9">
                                <h3 style="color: lightgoldenrodyellow">@Model.chatRooms[i].ChatRoomName</h3>
                                <p style="font-size: 12px;">Created by: @Model.chatRooms[i].Owner</p>
                            </div>
                            <div class"col-3" style="margin-left: auto;">
                                <a for="Join" class="nav-link text-dark" style="font-size: 30px;" asp-route-id="@Model.chatRooms[i].ChatRoomId" asp-page="/FightingCage/ThisChatroom"><i id="Join" class="fas fa-sign-in-alt"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <blockquote class="blockquote mb-0">
                            <div class"col-9">
                                <p>@Model.chatRooms[i].Description</p>
                            </div>
                        </blockquote>
                    </div>
                </div>
            </div>
        
    }
</div>

PoemonRepo/Pages/FightingCage/CreateChatroom.cshtml
@page
@model PokemonRepo.UI.Pages.FightingCage.CreateChatroomModel
@{
}

<body style="align-content: center; justify-content: center;">
    <div class="row" style="justify-content: center;">
        <div class="col-6" style="        Background-color: Black;
        border-radius: 40px;
        border: 5px solid yellow; ">
            <div class="Thiscontainer">
                <div class="d-flex justify-content-center h-100">
                    <div class="Thiscard">
                        <div class="Thiscard-header">
                            <h1 style="color: greenyellow">Create ChatRoom</h1>
                        </div>
                        <div class="card-body">
                            <form method="post">
                                <div class="Thisinput-group form-group">
                                    <div class="Thisinput-group-prepend">
                                        <span class="input-group-text"><i class="fas fa-comment"></i></span>
                                    </div>
                                    <input placeholder="Chatroom Name" asp-Action="" asp-for="@Model.ChatRoomName"/>
                                </div>
                                <div class="Thisinput-group form-group">
                                    <div class="Thisinput-group-prepend">
                                        <span class="input-group-text"><i class="fas fa-file-alt"></i></span>
                                    </div>
                                    <textarea placeholder="Description" style="width: 182px; min-height: 100px;" asp-for="@Model.ChatRoomDescription"></textarea>
                                </div>
                                <div class="form-group">
                                    <button class="btn float-right btn-outline-light">Create Room</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

PoemonRepo/Pages/FightingCage/EditProfile.cshtml
@page
@model PokemonRepo.UI.Pages.FightingCage.EditProfileModel
@{
}
<style>
    .image img {
        transition: all 0.5s
    }

    .card:hover .image img {
        transform: scale(1.2)
    }

    .btn {
        height: 240px;
        width: 240px;
        border-radius: 50%
    }

    .name {
        font-size: 22px;
        font-weight: bold
    }

    .idd {
        font-size: 14px;
        font-weight: 600
    }

    .idd1 {
        font-size: 12px
    }

    .number {
        font-size: 22px;
        font-weight: bold
    }

    .follow {
        font-size: 12px;
        font-weight: 500;
        color: #444444
    }

    .btn1 {
        height: 40px;
        width: 40px;
        border: none;
        background-color: transparent;
        color: #aeaeae;
        font-size: 15px;
        text-align: center;
        margin-top: 20px;
    }

    .text span {
        font-size: 13px;
        color: rgb(11 19 27);
        font-weight: 500
    }

    .icons i {
        font-size: 30px;
    }

    hr .new1 {
        border: 1px solid
    }

    .join {
        font-size: 14px;
        color: #a0a0a0;
        font-weight: bold
    }

    .date {
        background-color: #ccc
    }
</style>
<body>
    <div class="container bootstrap snippets bootdey" style="background: black; color: white; border: 5px solid yellow;">
        <h1 class="text-primary" style="color: yellow; margin-top: 20px;">Edit Profile</h1>
        <hr>
        <form method="post" enctype="multipart/form-data">
            <div class="row">
                <!-- left column -->
                <div class="col-md-3">
                    <div class="text-center">
                        <img src="~/Images/@Model.ProfileUser.PhotoPath" style="width: 200px; height: 250px;" asp-append-version="true">
                        <h6>Upload an other photo.</h6>
                        <input type="file" class="form-control" asp-for="@Model.Photo" value="@Model.ProfileUser.PhotoPath">
                    </div>
                </div>

                <!-- edit form column -->
                <div class="col-md-9 personal-info  justify-content-center">
                    <h3>Personal info</h3>
                    <div asp-validation-summary="All" class="text-danger"></div>


                    <div class="form-group">
                        <label class="col-lg-3 control-label">Username: </label>
                        <div class="col-lg-8">
                            <input class="form-control" type="text" value="@Model.ProfileUser.UserName" asp-for="@Model.Username">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-3 control-label">Email:</label>
                        <div class="col-lg-8">
                            <input class="form-control" type="email" value="@Model.ProfileUser.Email" asp-for="@Model.Email">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-3 control-label">Old Password:</label>
                        <div class="col-lg-8">
                            <input class="form-control" type="password" placeholder="*********" asp-for="@Model.Password">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-3 control-label">New password:</label>
                        <div class="col-lg-8">
                            <input class="form-control" type="password" placeholder="*********" asp-for="@Model.NewPassword">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-3 control-label">About me:</label>
                        <div class="col-lg-8">
                            <input class="form-control" type="text" value="@Model.ProfileUser.AboutMe" asp-for="@Model.AboutMe">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-3 control-label">Favorite Pokemon</label>
                        <div class="col-lg-8">
                            <div class="ui-select">
                                <select id="user_time_zone" class="form-control" value="@Model.ProfileUser.FavoritPokemon" asp-for="@Model.FavoritePok">
                                    @foreach (var pokemon in Model.pokemons)
                                    {
                                        <option>@pokemon</option>

                                    }
                                </select>
                            </div>
                            <div class="justify-content-end" style="margin-top: 10px;">
                                <button for="Join" class="submit text-dark float-right" style="font-size: 40px; background: transparent; outline: none;"><i id="Join" class="fas fa-save"></i></button>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </form>
    </div>
</body>

PoemonRepo/Pages/FightingCage/MyProfile.cshtml
@page
@model PokemonRepo.UI.Pages.FightingCage.MyProfile
@{
}
<style>
    .image img {
        transition: all 0.5s
    }

    .card:hover .image img {
        transform: scale(1.3)
    }

    .btn {
        height: 240px;
        width: 240px;
        border-radius: 50%
    }

    .name {
        font-size: 22px;
        font-weight: bold
    }

    .idd {
        font-size: 14px;
        font-weight: 600
    }

    .idd1 {
        font-size: 12px
    }

    .number {
        font-size: 22px;
        font-weight: bold
    }

    .follow {
        font-size: 12px;
        font-weight: 500;
        color: #444444
    }

    .btn1 {
        height: 40px;
        width: 40px;
        border: none;
        background-color: transparent;
        color: #aeaeae;
        font-size: 15px;
        text-align: center;
        margin-top: 20px;
    }

    .text span {
        font-size: 13px;
        color: rgb(11 19 27);
        font-weight: 500
    }

    .icons i {
        font-size: 30px;
    }

    hr .new1 {
        border: 1px solid
    }

    .join {
        font-size: 14px;
        color: #a0a0a0;
        font-weight: bold
    }

    .date {
        background-color: #ccc
    }
</style>

<div class="container mt-4 mb-4 p-3 d-flex justify-content-center">
    <div class="card p-4" style="border: 5px solid yellow; height: 700px; width: 400px; background: rgb(255,255,255); background: linear-gradient(0deg, rgba(255,255,255,1) 0%, rgba(149,149,149,1) 30%, rgba(78,78,78,1) 60%, rgba(0,0,0,1) 100%);">
        <div class=" image d-flex flex-column justify-content-center align-items-center">
            <button class="btn btn-secondary">
                <img src="~/Images/@Model.ProfileUser.PhotoPath" height="200" width="200" />
            </button>
            <span class="name mt-3">@Model.ProfileUser.UserName</span>
            <span class="idd"></span>
            <div class="text mt-3">
                <span>
                        @Model.ProfileUser.AboutMe

                    <br />
                    <br />
                        @Model.ProfileUser.FavoritPokemon
                </span>
            </div>
            <div class=" d-flex mt-2">
                    <a for="Join" class="nav-link text-dark" style="font-size: 40px;" asp-route-id="" asp-page="/FightingCage/EditProfile"><i id="Join" class="fas fa-user-edit"></i></a>
            </div>
            <hr />
            <div class=" px-2 rounded mt-4 date "> <span class="join">@Model.ProfileUser.JoinedDate.ToString("d")</span> </div>
        </div>
    </div>
</div>

PoemonRepo/Pages/FightingCage/ThisChatroom.cshtml
@page
@model PokemonRepo.UI.Pages.FightingCage.ThisChatroomModel
@{
}
<div class="row">
    <div class="col">
        <div class="row">
            <h3 style="color: antiquewhite">@Model.ThisChatroom.ChatRoomName</h3>
        </div>
        <div class="row">
            <p style="font-size: 12px; color: antiquewhite">Created by: @Model.ThisChatroom.Owner</p>
        </div>
    </div>
</div>
<div class="container justify-content-center overflow-auto"
     style="border: 5px solid yellow;
        max-height: 600px;
        max-width: 500px;">
    @foreach (var message in Model.Messages)
    {
        if (message.ChatMessageId == Model.ChatMessageid && Model.IsEditMode)
        {
            <form method="post">
                <div class="row" style=" margin-top:10px; background-color: white; max-width: 500px; border-radius: 28px; border-style: solid; border-color: white; margin: 3px 0 0 0">
                    <div col-3 style="min-width: 2cm;">
                        <img style=" min-height: 50px; max-height: 50px; max-width: 50px; min-width: 50px;border-radius: 25px; " src="~/Images/@message.User.PhotoPath" />
                    </div>
                    <div class="col-6" style="margin-left: 15px;">
                        <div class="row">
                            <div class="col" style="font-size: 20px; ">
                                @message.User.UserName
                            </div>
                        </div>
                        <div class="row" style="max-width: 100%; overflow-wrap: break-word;">
                            <div class="col">
                                <input type="text" style="width: 100%; height: 20px; overflow: auto;" value="@message.Message" asp-for="@Model.ThisMessage" />
                            </div>
                        </div>
                    </div>
                    <div class="col-3" style="margin-left: auto; margin-right: 10px; min-width: 2cm;">
                        <div class="row">
                            @message.Date.ToString("t")
                        </div>
                        <div class="row">
                            @if (message.User.Id == Model.AppUser.Id || Model.AppUser.UserName == "admin")
                            {

                                <input hidden value="@message.ChatMessageId" asp-for="ChatMessageid" />
                                <input hidden value="@Model.ThisChatroom.ChatRoomId" asp-for="ChatRoomid" />
                                <button asp-Page-handler="DoneEdit" type="submit"><i id="Join" class="fas fa-save"></i></button>

                            }
                        </div>
                    </div>
                </div>
            </form>
        }
        else
        {
            <div class="row" style=" margin-top:10px; background-color: white; max-width: 500px; border-radius: 28px; border-style: solid; border-color: white; margin: 3px 0 0 0">
                <div col-3 style="min-width: 2cm;">
                    <img style="min-height: 50px; max-height: 50px; max-width: 50px; min-width: 50px; border-radius: 25px; " src="~/Images/@message.User.PhotoPath" />
                </div>
                <div class="col-6" style="margin-left: 15px;">
                    <div class="row">
                        <div class="col" style="font-size: 20px; ">
                            @message.User.UserName
                        </div>
                    </div>
                    <div class="row" style="max-width: 100%; overflow-wrap: break-word;">
                        <div class="col">
                            @message.Message

                        </div>
                    </div>
                </div>
                <div class="col-3" style="margin-left: auto; margin-right: 10px; min-width: 2cm;">
                    <div class="row">
                        @message.Date.ToString("t")
                    </div>
                    <div class="row">
                        @if (message.User.Id == Model.AppUser.Id || Model.AppUser.UserName == "admin")
                        {
                            <form method="post">
                                <input hidden value="@message.ChatMessageId" asp-for="ChatMessageid" />
                                <input hidden value="@Model.ThisChatroom.ChatRoomId" asp-for="ChatRoomid" />
                                @if (!Model.IsEditMode)
                                {
                                    <button asp-Page-handler="Edit" type="submit"><i id="Join" class="fas fa-edit"></i></button>
                                    <button asp-page-handler="Delete" type="submit"><i id="Join" class="fas fa-trash"></i></button>
                                }
                            </form>
                        }
                    </div>
                </div>
            </div>
        }
    }

</div>
<div class="container" style="width: 100%; text-align: center">
    <div class="center" style="display: inline-block; margin: 0 auto; width: 550px;">
        <div class="row" style="margin-top: 10px;">
            <div class="col" style="align-content: center;">
                <form method="post">
                    <input hidden asp-for="@Model.ChatRoomid" value="@Model.ThisChatroom.ChatRoomId" />
                    <textarea palceholder="Message" asp-for="@Model.ThisMessage" style="Min-height:75px; Min-width: 300px; max-height:75px; max-width: 300px; padding:unset;"></textarea>
                    <button type="submit"><i id="Join" class="fas fa-paper-plane" style="width: 35px; padding:unset;"></i></button>
                </form>
            </div>
        </div>
    </div>
</div>